# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.5.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "boot2docker"

  config.vm.provider :virtualbox do |vb, override|
    override.vm.network "private_network", ip: "192.168.33.10"
  end
  config.vm.provider :parallels do |prl, override|
    override.vm.network "private_network", ip: "192.168.34.10"
  end

  config.vm.synced_folder ".", "/vagrant", type: "nfs"

  config.vm.provision :docker do |d|
    d.pull_images "busybox"
    d.run "busybox",
      cmd: "echo hello"
  end
end
