#!/bin/sh

print_usage() {
  echo "Usage: $(basename $0) <container id/name> [{command:-$SHELL} [argments...]]"
}

ID="$1"; shift
if [ -z "$ID" ] ; then
  print_usage && exit
fi

PID=$(docker inspect --format '{{.State.Pid}}' "$ID" 2> /dev/null)
if [ -z "$PID" ] ; then
  print_usage && exit
fi

echo "nsenter --target $PID --mount --uts --ipc --net --pid $@"
sudo sh -c "nsenter --target $PID --mount --uts --ipc --net --pid $@"
